@startuml DLT.WriterEncoder
interface ITraceEncoder
interface ITraceEncoderFactory

ITraceEncoderFactory -r- ITraceEncoder

class DltTraceEncoderFactory<TLine:DltTraceLineBase>
ITraceEncoderFactory <|.d. DltTraceEncoderFactory

class DltTraceEncoder<TLine:DltTraceLineBase>
ITraceEncoder <|.d. DltTraceEncoder

DltTraceEncoderFactory -r-> DltTraceEncoder : <<creates>>

interface IVerboseDltEncoder {
    +Encode(buffer: Span<byte>, line: DltTraceLineBase): int
}
class VerboseDltEncoder
IVerboseDltEncoder <|.d. VerboseDltEncoder

interface IArgEncoder {
    +Encode(buffer: Span<byte>, bool verbose, bool msbf, arg: IDltArg): int
}
class VerboseArgEncoder
IArgEncoder <|.d. VerboseArgEncoder

IVerboseDltEncoder *-r- IArgEncoder
VerboseDltEncoder *-r- VerboseArgEncoder

class BinaryIntArgEncoder
class HexIntArgEncoder
class SignedIntArgEncoder
class UnsignedIntArgEncoder
class BoolArgEncoder
class Float32ArgEncoder
class Float64ArgEncoder
class RawArgEncoder
class StringArgEncoder
class NonVerboseArgEncoder
class UnknownVerboseArgEncoder
IArgEncoder <|..d. BinaryIntArgEncoder
IArgEncoder <|..d. HexIntArgEncoder
IArgEncoder <|..d. SignedIntArgEncoder
IArgEncoder <|..d. UnsignedIntArgEncoder
IArgEncoder <|..d. BoolArgEncoder
IArgEncoder <|..d. Float32ArgEncoder
IArgEncoder <|..d. Float64ArgEncoder
IArgEncoder <|..d. RawArgEncoder
IArgEncoder <|..d. StringArgEncoder
IArgEncoder <|..d. NonVerboseArgEncoder
IArgEncoder <|..d. UnknownVerboseArgEncoder

VerboseArgEncoder *-d- BinaryIntArgEncoder
VerboseArgEncoder *-d- HexIntArgEncoder
VerboseArgEncoder *-d- SignedIntArgEncoder
VerboseArgEncoder *-d- UnsignedIntArgEncoder
VerboseArgEncoder *-d- BoolArgEncoder
VerboseArgEncoder *-d- Float32ArgEncoder
VerboseArgEncoder *-d- Float64ArgEncoder
VerboseArgEncoder *-d- RawArgEncoder
VerboseArgEncoder *-d- StringArgEncoder
VerboseArgEncoder *-d- NonVerboseArgEncoder
VerboseArgEncoder *-d- UnknownVerboseArgEncoder

DltTraceEncoder *-d- IVerboseDltEncoder

BinaryIntArgEncoder -d- BinaryIntDltArg : <<encodes>>
HexIntArgEncoder -d- HexIntDltArg : <<encodes>>
SignedIntArgEncoder -d- SignedIntDltArg : <<encodes>>
UnsignedIntArgEncoder -d- UnsignedIntDltArg : <<encodes>>
BoolArgEncoder -d- BoolDltArg : <<encodes>>
Float32ArgEncoder -d- Float32DltArg : <<encodes>>
Float64ArgEncoder -d- Float64DltArg : <<encodes>>
StringArgEncoder -d- StringDltArg : <<encodes>>
RawArgEncoder -d- RawDltArg : <<encodes>>
NonVerboseArgEncoder -d- RawDltArg : <<encodes\nverbose>>
NonVerboseArgEncoder -d- NonVerboseDltArg : <<encodes\nnonverbose>>
NonVerboseArgEncoder -d- UnknownVerboseDltArg : <<encodes>>
UnknownVerboseArgEncoder -d- UnknownVerboseDltArg : <<encodes>>
@enduml