//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJCP.App.DltDump.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJCP.App.DltDump.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error has occurred (unhandled exception)..
        /// </summary>
        internal static string ErrorAppUnhandledException {
            get {
                return ResourceManager.GetString("ErrorAppUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumping to: {0}.
        /// </summary>
        internal static string ErrorDumpBeingGenerated {
            get {
                return ResourceManager.GetString("ErrorDumpBeingGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} was not found..
        /// </summary>
        internal static string FilterApp_InputFileNotFound {
            get {
                return ResourceManager.GetString("FilterApp_InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified path is invalid {0}.
        /// </summary>
        internal static string FilterOpenError_DirectoryNotFound {
            get {
                return ResourceManager.GetString("FilterOpenError_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found {0}.
        /// </summary>
        internal static string FilterOpenError_FileNotFound {
            get {
                return ResourceManager.GetString("FilterOpenError_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open file {0} ({1})..
        /// </summary>
        internal static string FilterOpenError_InvalidFile {
            get {
                return ResourceManager.GetString("FilterOpenError_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O Exception occurred opening {0} ({1})..
        /// </summary>
        internal static string FilterOpenError_IOException {
            get {
                return ResourceManager.GetString("FilterOpenError_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path length too long {0}.
        /// </summary>
        internal static string FilterOpenError_PathTooLong {
            get {
                return ResourceManager.GetString("FilterOpenError_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient permissions opening {0} ({1}).
        /// </summary>
        internal static string FilterOpenError_Security {
            get {
                return ResourceManager.GetString("FilterOpenError_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient access privileges opening {0}.
        /// </summary>
        internal static string FilterOpenError_Unauthorized {
            get {
                return ResourceManager.GetString("FilterOpenError_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanging Indent must be zero or more.
        /// </summary>
        internal static string InfraFormatHangingIndentException {
            get {
                return ResourceManager.GetString("InfraFormatHangingIndentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent must be zero or more.
        /// </summary>
        internal static string InfraFormatIndentException {
            get {
                return ResourceManager.GetString("InfraFormatIndentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing string.
        /// </summary>
        internal static string InfraFormatMessageParseException {
            get {
                return ResourceManager.GetString("InfraFormatMessageParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width should be at least 10 characters including indent.
        /// </summary>
        internal static string InfraFormatWidthException {
            get {
                return ResourceManager.GetString("InfraFormatWidthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with the command line..
        /// </summary>
        internal static string OptionsError {
            get {
                return ResourceManager.GetString("OptionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DltDump Version: {0}.
        /// </summary>
        internal static string VersionDltDump {
            get {
                return ResourceManager.GetString("VersionDltDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DltDump Version: {0}, {1}.
        /// </summary>
        internal static string VersionDltDumpCopyright {
            get {
                return ResourceManager.GetString("VersionDltDumpCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   TraceReader: {0}.
        /// </summary>
        internal static string VersionTraceReader {
            get {
                return ResourceManager.GetString("VersionTraceReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   TraceReader.Dlt: {0}.
        /// </summary>
        internal static string VersionTraceReaderDlt {
            get {
                return ResourceManager.GetString("VersionTraceReaderDlt", resourceCulture);
            }
        }
    }
}
