@startuml DltPcapTraceDecoder

class DltPcapTraceDecoder
class DltPcapLegacyDecoder
class DltPcapNgDecoder
'class DltLineBuilder
'interface ITraceDecoder<DltTraceLineBase>

DltPcapTraceDecoder *-d- DltPcapLegacyDecoder
DltPcapTraceDecoder *-d- DltPcapNgDecoder
DltPcapLegacyDecoder -r- DltPcapNgDecoder : <<xor>>

enum TimeResolution {
    Microseconds
    Nanoseconds
}

class PcapFormat {
    IsLittleEndian: bool
    MajorVersion: int
    MinorVersion: int
    SnapLen: int
    FcsLen: int
    LinkType: int
    Resolution: TimeResolution
}
PcapFormat *-d- TimeResolution

DltPcapLegacyDecoder *-l- PcapFormat
DltPcapLegacyDecoder *-d- PacketDecoder

DltPcapNgDecoder *-d- PacketDecoder

class DltPcapNetworkTraceFilterDecoder {
    PacketTimeStamp: DateTime
}
PacketDecoder *-d- DltPcapNetworkTraceFilterDecoder

class DltTraceDecoder
DltPcapNetworkTraceFilterDecoder -l-|> DltTraceDecoder

interface IOutputStream
DltPcapNetworkTraceFilterDecoder o-r- IOutputStream

@enduml