@startuml Domain.Decoder.Writer

namespace Domain {
  class DltDumpTraceReaderFactory
  interface IOutputStream

  DltDumpTraceReaderFactory -r-> DltFileTraceFilterReaderFactory : <<instantiates>>

  class DltFileTraceFilterReaderFactory
  class TraceReader<DltTraceLineBase>
  class DltFileTraceFilterDecoder
  DltFileTraceFilterReaderFactory -d-> TraceReader : <<instantiates>>
  TraceReader *-d- DltFileTraceFilterDecoder
  DltFileTraceFilterDecoder -r-|> RJCP.Diagnostics.Log.Decoder.DltFileTraceDecoder
  DltFileTraceFilterDecoder o-d- IOutputStream
}

namespace RJCP.Diagnostics.Log.Decoder {
    class DltTraceDecoderBase {
        #OnPacket(line: DltTraceLineBase,\n ReadOnlySpan<byte> buffer, int headerOffset)
    }
    class DltFileTraceDecoder
    DltTraceDecoderBase <|-d- DltFileTraceDecoder
}
@enduml