@startuml Domain.Decoder.Writer

namespace Domain {
  class DltTraceDecoderFactory
  interface IOutputStream

  DltTraceDecoderFactory -r-> DltFileTraceFilterDecoder : <<instantiates>>

  class DltFileTraceFilterDecoder
  DltFileTraceFilterDecoder -r-|> RJCP.Diagnostics.Log.Decoder.DltFileTraceDecoder
  DltFileTraceFilterDecoder o-d- IOutputStream
}

namespace RJCP.Diagnostics.Log.Decoder {
    class DltTraceDecoderBase {
        #OnPacket(line: DltTraceLineBase,\n ReadOnlySpan<byte> buffer, int headerOffset)
    }
    class DltFileTraceDecoder
   DltTraceDecoderBase <|-d- DltFileTraceDecoder
}

@enduml