@startuml Domain.InputStream_Sequence
autoactivate on

FilterApp -> IInputStreamFactory : Create(uri)
return IInputStream

loop Process File

    FilterApp -> IInputStream : Open()
    return

    alt inputStream.RequiresConnection == true

        loop !connected && (retries < 0 || connectAttempt <= retries)

            FilterApp -> IInputStream : ConnectAsync()
            return connected: bool

        end

    end

    alt Stream based input

        FilterApp -> IInputStream : get_InputStream()
        return Stream

    else Packet based input

        FilterApp -> IInputStream : get_InputPacket()
        return IPacket

    end

    note over FilterApp
        Process Input
    end note

    FilterApp -> IInputStream : Close()
    return

end

FilterApp -> IInputStream : Dispose()
return

@enduml