@startuml Layers
allowmixing

skinparam class {
    fontColor Transparent
    stereotypeFontColor Transparent
}


rectangle Root {
    class A11111 { }
}

rectangle Application {
    class A33333 { }
}

rectangle Services {
    class A44444 { }
}

rectangle "Domain Model" as Domain {
    class A55555 { }
}

rectangle View {
    class A22222 { }
}

rectangle Infrastructure {
    class A66666 { }
}

rectangle Framework {
    class A77777 { }
}

Root -r-> View
View -r-> Application
Application -r-> Services
Services -r-> Domain
Domain -r-> Infrastructure
Infrastructure -r-> Framework

@enduml